// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Simply_add_a_license.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimply_add_a_licensePackageString = "1fed752c-4993-400a-908c-3332bf36f632";
        public static Guid guidSimply_add_a_licensePackage = new Guid(guidSimply_add_a_licensePackageString);

        public const string guidSimply_add_a_licensePackageCmdSetString = "25afcc80-53c9-469e-b4f5-77edf8d8fe72";
        public static Guid guidSimply_add_a_licensePackageCmdSet = new Guid(guidSimply_add_a_licensePackageCmdSetString);

        public const string guidImagesString = "c285c5b1-38d7-47c4-a777-b51a68a5a00e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Simply_add_a_licenseId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}